### ISSUE TITLE
HomeBridge crash caused by open paths

### ISSUE THREAD

**Issue by rooi** [luisiam/homebridge-openpaths#1]
Hi,

This morning it noticed this crash. I did not look into it further, but logging it here for now.

Roy

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/homebridge-openpaths/index.js:165:28)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-openpaths/node_modules/openpaths-api/node_modules/request/request.js:236:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-openpaths/node_modules/openpaths-api/node_modules/request/request.js:1142:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-openpaths/node_modules/openpaths-api/node_modules/request/request.js:1096:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)

**Comment by luisiam** [comment]
I saw that couple days ago and I was working on a fix, together with couple issues I found. Just push a commit to include the fix.
